module.exports = {
  reactStrictMode: true,
  transpilePackages: ["@minimal/config"],
  experimental: {
    scrollRestoration: true,
  },
  // Sitemap is now generated by next-sitemap at build time
  redirects: async () => [
    // Consolidate /calendars/preview/* to /calendars/*
    {
      source: "/calendars/preview/:year",
      destination: "/calendars/:year",
      permanent: true,
    },
    {
      source: "/calendars/preview/:year/:theme",
      destination: "/calendars/:year/:theme",
      permanent: true,
    },
    {
      source: "/calendars/preview/:year/:theme/:locale",
      destination: "/calendars/:year/:theme/:locale",
      permanent: true,
    },
  ],
};
