module.exports = {
  reactStrictMode: true,
  transpilePackages: ["@minimal/config"],
  experimental: {
    scrollRestoration: true,
  },
  // Sitemap is now generated by next-sitemap at build time
  redirects: async () => [
    // Consolidate /calendars/preview/* to /calendars/*
    {
      source: "/calendars/preview/:year",
      destination: "/calendars/:year",
      permanent: true,
    },
    {
      source: "/calendars/preview/:year/:theme",
      destination: "/calendars/:year/:theme",
      permanent: true,
    },
    {
      source: "/calendars/preview/:year/:theme/:locale",
      destination: "/calendars/:year/:theme/:locale",
      permanent: true,
    },
    // Legacy theme slug: /calendars/<year>/simple → /calendars/<year>/editorial.
    // Constrain :year to 4 digits so this doesn't swallow sibling routes like
    // /calendars/style/simple (where :year would otherwise match "style").
    {
      source: "/calendars/:year(\\d{4})/simple",
      destination: "/calendars/:year/editorial",
      permanent: true,
    },
    {
      source: "/calendars/:year(\\d{4})/simple/:locale",
      destination: "/calendars/:year/editorial/:locale",
      permanent: true,
    },
  ],
};
