/** @type {import('next-sitemap').IConfig} */
module.exports = {
  siteUrl: process.env.SITE_URL || "https://useminimal.com",
  generateRobotsTxt: true,
  exclude: ["/print", "/api/*", "/portal", "/og-preview"],

  // NOTE: `path` is the full URL path as generated by Next.js
  // e.g., "/calendars/2025/simple/en" - adjust matching accordingly
  transform: async (config, path) => {
    const currentYear = new Date().getFullYear();

    // Highest priority: landing, habit tracker
    if (path === "/" || path === "/habit-tracker") {
      return { loc: path, changefreq: "weekly", priority: 1.0 };
    }

    // High priority: main calendars hub
    if (path === "/calendars") {
      return { loc: path, changefreq: "weekly", priority: 0.95 };
    }

    // High priority: intent pages (/calendars/intent/*)
    if (path.startsWith("/calendars/intent/")) {
      return { loc: path, changefreq: "monthly", priority: 0.95 };
    }

    // High priority: current year pages (/calendars/2025, /calendars/2025/simple, etc.)
    if (path.startsWith(`/calendars/${currentYear}`)) {
      return { loc: path, changefreq: "monthly", priority: 0.9 };
    }

    // Medium priority: future years (current+1 to current+3)
    for (let i = 1; i <= 3; i++) {
      if (path.startsWith(`/calendars/${currentYear + i}`)) {
        return { loc: path, changefreq: "monthly", priority: 0.7 };
      }
    }

    // Medium priority: hub pages (languages, formats index)
    if (path === "/calendars/languages" || path === "/calendars/formats") {
      return { loc: path, changefreq: "monthly", priority: 0.8 };
    }

    // Medium-low priority: format detail & week-start pages
    if (
      path.startsWith("/calendars/formats/") ||
      path.startsWith("/calendars/week-start/")
    ) {
      return { loc: path, changefreq: "monthly", priority: 0.6 };
    }

    return { loc: path, changefreq: "monthly", priority: 0.5 };
  },

  robotsTxtOptions: {
    policies: [
      {
        userAgent: "*",
        allow: "/",
        disallow: ["/print", "/api/", "/portal"],
      },
    ],
  },
};
