export type SupportedLocale = {
  code: string;
  name: string;
  englishName: string;
  emoji: string;
  outputCalendar: string;
  numberingSystem: string;
};

export type Theme = "simple";

export const SupportedLocales: SupportedLocale[] = [
  {
    code: "en",
    name: "English",
    englishName: "English",
    emoji: "🇺🇸",
    outputCalendar: "gregory",
    numberingSystem: "latn",
  },
  {
    code: "fr",
    name: "Français",
    englishName: "French",
    emoji: "🇫🇷",
    outputCalendar: "gregory",
    numberingSystem: "latn",
  },
  {
    code: "de",
    name: "Deutsch",
    englishName: "German",
    emoji: "🇩🇪",
    outputCalendar: "gregory",
    numberingSystem: "latn",
  },
  {
    code: "es",
    name: "Español",
    englishName: "Spanish",
    emoji: "🇪🇸",
    outputCalendar: "gregory",
    numberingSystem: "latn",
  },
  {
    code: "it",
    name: "Italiano",
    englishName: "Italian",
    emoji: "🇮🇹",
    outputCalendar: "gregory",
    numberingSystem: "latn",
  },
  {
    code: "pt",
    name: "Português",
    englishName: "Portuguese",
    emoji: "🇵🇹",
    outputCalendar: "gregory",
    numberingSystem: "latn",
  },
  {
    code: "pl",
    name: "Polski",
    englishName: "Polish",
    emoji: "🇵🇱",
    outputCalendar: "gregory",
    numberingSystem: "latn",
  },
  {
    code: "lv",
    name: "Latviešu",
    englishName: "Latvian",
    emoji: "🇱🇻",
    outputCalendar: "gregory",
    numberingSystem: "latn",
  },
  {
    code: "nn",
    name: "Norsk",
    englishName: "Norwegian",
    emoji: "🇳🇴",
    outputCalendar: "gregory",
    numberingSystem: "latn",
  },
  {
    code: "cs",
    name: "Čeština",
    englishName: "Czech",
    emoji: "🇨🇿",
    outputCalendar: "gregory",
    numberingSystem: "latn",
  },
  {
    code: "uk",
    name: "Українська",
    englishName: "Ukrainian",
    emoji: "🇺🇦",
    outputCalendar: "gregory",
    numberingSystem: "latn",
  },
  {
    code: "hr",
    name: "Hrvatski",
    englishName: "Croatian",
    emoji: "🇭🇷",
    outputCalendar: "gregory",
    numberingSystem: "latn",
  },
  {
    code: "sk",
    name: "Slovenčina",
    englishName: "Slovak",
    emoji: "🇸🇰",
    outputCalendar: "gregory",
    numberingSystem: "latn",
  },
  {
    code: "sl",
    name: "Slovenščina",
    englishName: "Slovenian",
    emoji: "🇸🇮",
    outputCalendar: "gregory",
    numberingSystem: "latn",
  },
  {
    code: "th",
    name: "ไทย",
    englishName: "Thai",
    emoji: "🇹🇭",
    outputCalendar: "buddhist",
    numberingSystem: "thai",
  },
  {
    code: "da",
    name: "Dansk",
    englishName: "Danish",
    emoji: "🇩🇰",
    outputCalendar: "gregory",
    numberingSystem: "latn",
  },
  {
    code: "nl",
    name: "Nederlands",
    englishName: "Dutch",
    emoji: "🇳🇱",
    outputCalendar: "gregory",
    numberingSystem: "latn",
  },
  {
    code: "fi",
    name: "Suomi",
    englishName: "Finnish",
    emoji: "🇫🇮",
    outputCalendar: "gregory",
    numberingSystem: "latn",
  },
  {
    code: "is",
    name: "Íslenska",
    englishName: "Icelandic",
    emoji: "🇮🇸",
    outputCalendar: "gregory",
    numberingSystem: "latn",
  },
  {
    code: "hu",
    name: "Magyar",
    englishName: "Hungarian",
    emoji: "🇭🇺",
    outputCalendar: "gregory",
    numberingSystem: "latn",
  },
  {
    code: "ro",
    name: "Română",
    englishName: "Romanian",
    emoji: "🇷🇴",
    outputCalendar: "gregory",
    numberingSystem: "latn",
  },
  {
    code: "sv",
    name: "Svenska",
    englishName: "Swedish",
    emoji: "🇸🇪",
    outputCalendar: "gregory",
    numberingSystem: "latn",
  },
  {
    code: "tr",
    name: "Türkçe",
    englishName: "Turkish",
    emoji: "🇹🇷",
    outputCalendar: "gregory",
    numberingSystem: "latn",
  },
  {
    code: "ru",
    name: "Русский",
    englishName: "Russian",
    emoji: "🇷🇺",
    outputCalendar: "gregory",
    numberingSystem: "latn",
  },
  {
    code: "ko",
    name: "한국어",
    englishName: "Korean",
    emoji: "🇰🇷",
    outputCalendar: "gregory",
    numberingSystem: "latn",
  },
  {
    code: "hi",
    name: "हिन्दी",
    englishName: "Hindi",
    emoji: "🇮🇳",
    outputCalendar: "gregory",
    numberingSystem: "latn",
  },
  {
    code: "el",
    name: "Ελληνικά",
    englishName: "Greek",
    emoji: "🇬🇷",
    outputCalendar: "gregory",
    numberingSystem: "latn",
  },
  {
    code: "fa",
    name: "فارسی",
    englishName: "Persian",
    emoji: "🇮🇷",
    outputCalendar: "persian",
    numberingSystem: "arab",
  },
  {
    code: "ar",
    name: "العربية",
    englishName: "Arabic",
    emoji: "🇸🇦",
    outputCalendar: "islamic",
    numberingSystem: "arab",
  },
  {
    code: "he",
    name: "עברית",
    englishName: "Hebrew",
    emoji: "🇮🇱",
    outputCalendar: "hebrew",
    numberingSystem: "latn",
  },
  {
    code: "ja",
    name: "日本語",
    englishName: "Japanese",
    emoji: "🇯🇵",
    outputCalendar: "japanese",
    numberingSystem: "latn",
  },
  {
    code: "zh",
    name: "中文",
    englishName: "Chinese",
    emoji: "🇨🇳",
    outputCalendar: "chinese",
    numberingSystem: "latn",
  },
  // {
  //   code: "saz",
  //   name: "Sourashtra",
  //   englishName: "Sazande",
  //   emoji: "🇸🇿",
  //   outputCalendar: "gregory",
  //   numberingSystem: "latn",
  // },
  // countries below have wierd month short names, need different layout
  // { code: "lt", name: "Lietuvių", englishName: "Lithuanian", emoji: "🇱🇹" },
];
